name: Build and deploy
on:
  push:

    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: Install dependencies
        run:  npm install

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
  

      - name: Restart api server
        run:   pm2 restart demo

      - name: Notify success deployment
        run: echo "Deployment complete"


